import LocalizedStrings from 'react-localization';

/*
ğ – \u011f
Ğ – \u011e
ı – \u0131
İ – \u0130
ö – \u00f6
Ö – \u00d6
ü – \u00fc
Ü – \u00dc
ş – \u015f
Ş – \u015e
ç – \u00e7
Ç – \u00c7
*/

let localization = new LocalizedStrings({
  en: {
    email: 'Email',
    password: 'Password',
    login: 'Login',
    required: 'This field is required',
    policyNo: 'Policy No',
    startDate: 'Start Date',
    endDate: 'End Date',
    submit: 'Submit',
    cancel: 'Cancel',
    addPolicy: 'Add Policy',
    addCustomer: 'Add Customer',
    customer: 'Customer',
    customers: 'Customers',
    policies: 'Policies',
    displayName: 'Display Name',
    tcVergiNo: 'Tax Number',
    contactNumber: 'Contact Number',
    corporate: 'Corporate',
    name: 'Name',
    surname: 'Surname',
    title: 'Title',
    failedFormat: 'Wrong format',
    newCustomer: 'New Customer',
    customerDetail: 'Customer Detail',
    newPolicy: 'New Policy',
    back: 'Back',
    policyType: 'Policy Type',
    selectOption: 'PLEASE SELECT',
    allrisk: 'ALL RISK',
    dask: 'DASK',
    trafic: 'TRAFIC',
    kasko: 'KASKO',
    proficiencyResponsibility: 'PROFICIENCY RESPONSIBILITY',
    home: 'HOME',
    fire: 'FIRE',
    plateNo: 'Plate No',
    documentNo: 'Document No',
    insuranceFee: 'Insurance Fee',
    net: 'Net',
    gross: 'Gross',
    comissionRate: 'Comission Rate',
    insuranceCompany: 'Insurance Company',
    insuranceCompanies: 'Insurance Companies',
    addAgency: 'Add Agency',
    newAgency: 'New Agency',
    deleteAgency: 'Delete Agency',
    editAgency: 'Edit Agency',
    agencyDetail: 'Agency Detail',
    agencies: 'Agencies',
    dateFormat: 'DD/MM/YYYY',
    agency: 'Agency',
    dashboard: 'Home',
    currencySign: 'GB',
    edit: 'Edit',
    delete: 'Delete',
    list: 'List',
    detail: 'Detail',
    deleteConfirmation: 'Are you sure to delete this record?',
    deleteRejectPolicies: 'You can not delete this record. You should delete the related policies before.',
    signout: 'Sign out',
    signup: 'Sign up',
    user: 'User',
    loading: 'Loading',
    remember: 'Remember',
    forgetPassword: 'Forgot Password?',
    needAccount: 'Need an Account?',
    or: 'or',
    username: 'Username',
    alreadyHaveAccount: 'Already have an account?',
    invalidEmail: 'Invalid email address',
    whoops404: 'Whoops! 404!',
    pageNotFound: 'This page was not found.',
    noOwner: 'No owner'

  },
  tr: {
    email: 'E-posta',
    password: 'Parola',
    login: 'Giri\u015f',
    required: 'Bu alan zorunludur',
    policyNo: 'Poli\u00e7e No',
    startDate: 'Ba\u015flang\u0131\u00e7 Tarihi',
    endDate: 'Biti\u015f Tarihi',
    submit: 'Kaydet',
    cancel: '\u0130ptal',
    addPolicy: 'Poli\u00e7e Ekle',
    addCustomer: 'M\u00fc\u015fteri Ekle',
    customer: 'M\u00fc\u015fteri',
    customers: 'M\u00fc\u015fteriler',
    policies: 'Poli\u00e7eler',
    displayName: 'G\u00f6r\u00fcn\u00fcr Ad\u0131',
    tcVergiNo: 'TC/Vergi No',
    contactNumber: '\u0130leti\u015fim No',
    corporate: 'T\u00fczel',
    name: 'Ad\u0131',
    surname: 'Soyad\u0131',
    title: 'Unvan\u0131',
    failedFormat: 'Format hatal\u0131',
    newCustomer: 'Yeni M\u00fc\u015fteri',
    customerDetail: 'M\u00fc\u015fteri Detay\u0131',
    newPolicy: 'Yeni Poli\u00e7e',
    back: 'Geri',
    policyType: 'Poli\u00e7e T\u00fcr\u00fc',
    selectOption: 'L\u00dcTFEN SE\u00c7\u0130N\u0130Z',
    allrisk: 'ALL R\u0130SK',
    dask: 'DASK',
    trafic: 'TRAF\u0130K',
    kasko: 'KASKO',
    proficiencyResponsibility: 'MESLEK\u0130 SORUMLULUK',
    home: 'KONUT',
    fire: 'YANGIN',
    plateNo: 'Plaka No',
    documentNo: 'Ruhsat/Belge No',
    insuranceFee: 'Prim',
    net: 'Net',
    gross: 'Br\u00fct',
    comissionRate: 'Komisyon Oran\u0131',
    insuranceCompany: 'Sigorta \u015eirketi',
    insuranceCompanies: 'Sigorta \u015eirketleri',
    addAgency: 'Acente Ekle',
    newAgency: 'Yeni Acente',
    deleteAgency: 'Acente Silme',
    editAgency: 'Acente D\u00fczenleme',
    agencies: 'Acenteler',
    agencyDetail: 'Acente Detay\u0131',
    dateFormat: 'GG/AA/YYYY',
    agency: 'Acente',
    dashboard: 'Anasayfa',
    currencySign: 'TL',
    edit: 'D\u00fczenle',
    delete: 'Sil',
    list: 'Liste',
    detail: 'Detay',
    deleteConfirmation: 'Bu kayd\u0131 silmek istedi\u011finizden emin misiniz?',
    deleteRejectPolicies: 'Bu kayd\u0131 silemezsiniz. \u00d6ncelikle ba\u011fl\u0131 poli\u00e7eleri silmeniz gerekmektedir.',
    signout: '\u00c7\u0131k\u0131\u015f',
    signup: 'Kaydol',
    user: 'Kullan\u0131c\u0131',
    loading: 'Y\u00fckleniyor',
    remember: 'Beni hat\u0131rla',
    forgetPassword: '\u015eifre hat\u0131rlat',
    needAccount: 'Hesaba m\u0131 ihyitac\u0131n var?',
    or: 'veya',
    username: 'Kullan\u0131c\u0131 ad\u0131',
    alreadyHaveAccount: 'Zaten hesab\u0131n var m\u0131?',
    invalidEmail: 'Hatal\u0131 e-posta adresi',
    whoops404: 'Aman Yarabbim! 404!',
    pageNotFound: 'B\u00f6yle bir sayfa yok. Wallahi de billahi de yok!',
    noOwner: 'Sahibi yok'
  }
});

localization.setLanguage('tr');

export default localization;
